### Indentation examples

In [3]:
def f(param):
    #body of the function
    
    return return_value


In [4]:
for n in range(2):
    for i in range(2):
        for j in range(2):
            print(n,i,j)



0 0 0
0 0 1
0 1 0
0 1 1
1 0 0
1 0 1
1 1 0
1 1 1


# Day 2

- numpy:
    - arrays as special lists
    - random numbers
    - a few basic functions
    - more dimensions and axis
- Recursive definititions (arrays, lists and dictionaries)
- Functions

In [152]:
import numpy as np

## Random

In [23]:
a = np.random.randint(10,size=10)

In [24]:
type(a)

numpy.ndarray

In [29]:
b = list(a)
b
b * 2

[4, 7, 9, 5, 4, 2, 1, 4, 6, 2, 4, 7, 9, 5, 4, 2, 1, 4, 6, 2]

In [30]:
a * 2

array([ 8, 14, 18, 10,  8,  4,  2,  8, 12,  4])

In [ ]:
r

In [33]:
M = np.random.randint(10,size=(10,3))
M.shape

(10, 3)

In [80]:
R = np.random.rand(10,3)
R

array([[0.82058345, 0.04046167, 0.93858276],
       [0.9836274 , 0.95499203, 0.14735302],
       [0.95996093, 0.64601069, 0.67176406],
       [0.44232589, 0.53274451, 0.73146526],
       [0.5636268 , 0.46799536, 0.05722776],
       [0.12210405, 0.84783661, 0.95959036],
       [0.53867673, 0.27438682, 0.87718307],
       [0.20586496, 0.21020783, 0.94550469],
       [0.49558941, 0.50728004, 0.38504717],
       [0.6918886 , 0.17122907, 0.95710329]])

You access individual or multiple elements of an array with the square brackets

First 6 elements on axis 0

In [81]:
R[:6,1]

array([0.04046167, 0.95499203, 0.64601069, 0.53274451, 0.46799536,
       0.84783661])

Last 4 elements on axis 0

In [84]:
R[6:,1]

array([0.27438682, 0.21020783, 0.50728004, 0.17122907])

In [85]:
R[R.shape[0]-4:,1]

array([0.27438682, 0.21020783, 0.50728004, 0.17122907])

This is the cleanest way allowed in python

In [ ]:
R[-4:,1,0]

What if we wanted numbers between -2 and 1

In [100]:
R = np.random.rand(10,3)*3 - 2
R

array([[ 0.99011616, -1.2424025 , -0.34134239],
       [-1.84522647, -1.74574115, -0.41877977],
       [-0.06691887, -1.86814842, -1.84505817],
       [ 0.39630621,  0.35068331, -0.25188041],
       [ 0.50074973, -0.75061581,  0.1332561 ],
       [ 0.97359969, -1.96890433, -1.00691963],
       [-1.59476656,  0.8426414 , -1.39104429],
       [-0.97430881, -1.8393194 , -1.74305521],
       [ 0.44993105,  0.67948844, -1.71731648],
       [ 0.93119643,  0.304387  , -0.27238937]])

In [105]:
R = np.random.uniform(low=-2,high=1,size=(10,3))
R

array([[ 0.09857283, -1.2864527 , -0.80002624],
       [-0.33467743,  0.22841515, -0.80222613],
       [-1.33064224, -0.9451227 , -0.299101  ],
       [-1.45836939,  0.61491468, -0.13198495],
       [ 0.91636329, -0.23589672, -1.36262441],
       [-1.33629029,  0.47279527, -1.71831785],
       [ 0.96543939,  0.19663372, -0.97934569],
       [ 0.56994753,  0.02262626, -0.70452843],
       [-0.34942114,  0.26639317, -0.59578115],
       [-0.37475233, -1.9794818 , -1.55021432]])

Or maybe we want normally distributed random number

In [98]:
np.random.normal(loc=5,scale=3,size=(10,3))

array([[ 4.57182015,  3.41292841,  1.63113848],
       [10.93131685,  3.27738597,  8.49563976],
       [ 2.92781428,  8.94440596,  4.06419614],
       [ 0.60973325,  5.72603002,  1.42299861],
       [ 4.62496498,  8.84962939,  9.10472138],
       [ 7.43567336,  7.84971363,  4.67439106],
       [ 2.19543647,  0.24596138, -2.11082219],
       [ 8.99682168,  5.47687497,  7.98273385],
       [ 4.74513254,  5.24416621,  7.48749976],
       [ 9.77623225,  2.95256403, -0.39758368]])

## There are more ways to get arrays out of numpy than random numbers

In [114]:
Z = np.zeros(shape=(3,3))
Z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [115]:
O = np.ones((3,3))*5
O

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [117]:
np.array([i for i in range(5)])

array([0, 1, 2, 3, 4])

In [124]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [121]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [120]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [128]:
np.linspace(-1,1,11)

array([-1. , -0.8, -0.6, -0.4, -0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

What if we want to create an array with the same shape as another one

In [131]:
R.shape

(10, 3)

In [135]:
np.zeros_like(R)
# or
# np.empty_like(R)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# Arrays as special lists

With numpy arrays we can perfom mathematical operations, which are carried element by element

In [138]:
dt = 0.01 #s
Nt = 100

t = np.arange(0,Nt)*dt + dt

y = t**2 + np.sqrt(t) + np.log(2*t) + np.sin(t*3) + np.cos(t)

## What about vector operations

In [144]:
a = np.random.rand(3)
b = a + 0.3 * np.random.rand(3)
print(x1,x2)

[0.79221743 0.96583601 0.33997331] [0.8651765  1.04685328 0.56982802]


$a = (a_1,a_2,a_3),\; b = (b_1,b_2,b_3) $

$a\cdot b = a_1*b_1 + a_2*b_2 +a_3*b_3$  

In [145]:
np.dot(x1,x2)

1.8902228083112347

In [146]:
O = np.random.rand(3,3)

In [147]:
np.dot(O,x1)

array([0.39576994, 1.47194822, 1.23438893])

## Few basic functions: average and standard deviation

In [156]:
Nt = 10000
Ne = 50
Np = 20

data = np.random.rand(Np,Ne,Nt)

In [157]:
data.shape

(20, 50, 10000)

In [158]:
np.average(data)

0.5000709706894322

In [165]:
t_average = np.average(data,axis=2)
t_average.shape

(20, 50)

In [166]:
t_std = np.std(data,axis=2)
t_std.shape

(20, 50)

In [167]:
p_average = np.average(data,axis=0)

In [168]:
p_average.shape

(50, 10000)

In [172]:
pt_average = np.average(p_average,axis=1)

In [174]:
pt_average.shape

(50,)

# Accessing arrays

In [176]:
data.shape

(20, 50, 10000)

In [177]:
sel_p = 5
# I want to select the data of one participant, at each electrode and timepoint
sel_data = data[sel_p,:,:]
sel_data.shape

(50, 10000)

In [106]:
# Now we want the same patient but only every fifth electrode
sel_data = data[sel_p,::5,:]
sel_data.shape

(10, 10000)

In [184]:
a = np.arange(0,10)
a[-2:]

array([8, 9])

In [185]:
# Now we want the patients from 7 to 10
sel_data = data[7:10,:,:]
sel_data.shape

(3, 50, 10000)

## Ranges

In [186]:
participants = np.arange(0,Np)
participants



array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [187]:
selected_participants = [13,16,7,5]
sel_data = data[selected_participants,:,:]
sel_data.shape

(4, 50, 10000)

What if I want to look at part of the dataset that satisfies certain condition

In [193]:
np.where(data > 0.99)

(array([ 0,  0,  0, ..., 19, 19, 19], dtype=int64),
 array([ 0,  0,  0, ..., 49, 49, 49], dtype=int64),
 array([  23,  134,  230, ..., 9885, 9905, 9933], dtype=int64))

In [194]:
data[np.where(data > 0.99)].shape

(100426,)

In [196]:
data[data > 0.99]

array([0.99506783, 0.99992539, 0.99349565, ..., 0.99544929, 0.99281999,
       0.9945607 ])

### Save and load data

In [224]:
np.savetxt('C:/Users/deangelis/Documents/python4onwar/2 - Basics and numpy/test.txt',data[:,:,0])

In [226]:
loaded = np.loadtxt('C:/Users/deangelis/Documents/python4onwar/2 - Basics and numpy/test.txt')

In [228]:
loaded.shape

(20, 50)

# Functions

Standard function definition

In [198]:
def str2int(s):
    
    return int(s)



def my_function(par1,par2,par3=1):
    
    par1 = str2int(par1)
    par2 = str2int(par2)
    
    product = par1*par2*par3
    
    return product


def list_product(A):
    """Computes the product of the elements in a list
    
    A : list of parameters to be multiplied   
    """
    
    prod = 1
    
    for el in A:
        prod = prod * el
        # prod *= el Exactly equivalent above
        
    return prod

In [206]:
a = np.random.rand(3,2)

In [207]:
a

array([[0.37324347, 0.90715305],
       [0.20046387, 0.56808572],
       [0.71062954, 0.6425304 ]])

In [214]:
np.sum(a,axis=0)

array([1.28433688, 2.11776918])

In [157]:
my_function(4,'5')

20

In [162]:
list_product([1,4,7,2])

56

lambda functions are just functions but defined in a more compact way

In [232]:
pow2 = lambda x : x**2

In [233]:
pow2(2)

4

In [234]:
def pow2(x):
    return x**2

In [235]:
pow2(2)

4

The same thing.

### Another quick look at comprehension lists Comprehension lists (or dictionaries)

In [220]:
A = []

for i in range(10):
    A.append(i)

A

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [169]:
A = [i for i in range(10)]
A

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [174]:
evenodd = {0:'even',1:'odd'}
D = {i:evenodd[i%2] for i in range(37)}

In [175]:
A = {i:[k for k in range(20)] for i in range(10) }

In [176]:
A

{0: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
 1: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
 2: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
 3: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
 4: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
 5: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
 6: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
 7: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
 8: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
 9: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]}